export  const HEADING_TEXT = 'By Devi Enterprises';
export const COMPLETE_SOLUTION_TEXT = 'Complete Bath Fitting Solutions.';
export const LOGIN_TEXT = 'Login';
export const INVALID_EMAIL_ADDRESS_ERROR_TEXT = 'Invalid Email Address';
export const FORGOT_PASSWORD_TEXT = 'Forgot Password ?';
export const REGISTER_HERE_TEXT = 'Register here.';
export const ENTER_YOUR_REGISTERED_MOBILE_NUMBER_TEXT = 'Enter your Registered Mobile number.';
export const SENT_OTP_TEXT = 'Send OTP';
export const OTP_VERIFICATION_TEXT = 'OTP Verification';
export const ENTER_YOUR_OTP_SENT_TO_YOUR_REGISTERED_MOBILE = 'Enter Your OTP Sent to  your registered mobile.'
export const RESEND_OPT_TEXT = 'Resend OTP';
export const VERIFY_TEXT = 'Verify';
export const PASSWORD_RESET_TEXT = 'Password Reset';
export const RESET_TEXT = 'Reset';
export const CONFORM_PASSWORD_TEXT = 'Confirm Password'