export const ORDER_TEXT = 'Orders';
export const ORDER_SUMMARY = 'Order Summary';
export const DELIVERY_ADDRESS = 'Delivery Address';
export const DELIVERY_DETAILS = 'Delivery Details';
export const DELIVERY_IN_TEXT =
  'Delivery in 24 hours once the order is placed.';
export const DELIVERY_HOURS = 'Business hours (9AM- 5PM)';
export const PRICE_DETAILS = 'Price Details';
export const TOTAL_PRICE = 'Total Price';
export const OUTPUT_CGST = 'Output CGST';
export const OUTPUT_SGST = 'Output SGST';
export const TOTAL = 'Total';
export const SAVE_DRAFR = 'SAVE DRAFT';
export const PLACE_ORDER = 'PLACE ORDER';
export const PROCEED_TEXT = '  PROCEED  ';
export const EDIT_QUANTITY = 'Edit Quantity';
export const SAVE_TEXT = 'SAVE';
export const ORDER_PLACED = 'Order Placed';
export const YOU_CAN_SEE = 'You can see your listings in orders tab';
export const ORDER_DRAFTED_TEXT = 'Order Drafted';
export const YOU_CAN_SEE_YOUR_LISTING_IN_ORDER_TAB = 'You can see your listings in orders tab'
